# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pattern2EVCD_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ClockPinName_label = QtWidgets.QLabel(self.centralwidget)
        self.ClockPinName_label.setGeometry(QtCore.QRect(431, 200, 100, 20))
        self.ClockPinName_label.setObjectName("ClockPinName_label")
        self.Period_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Period_lineEdit.setGeometry(QtCore.QRect(230, 200, 180, 20))
        self.Period_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Period_lineEdit.setObjectName("Period_lineEdit")
        self.ClockPinName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ClockPinName_lineEdit.setGeometry(QtCore.QRect(550, 200, 180, 20))
        self.ClockPinName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ClockPinName_lineEdit.setObjectName("ClockPinName_lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 40, 620, 50))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.SingleFile_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.SingleFile_radioButton.setGeometry(QtCore.QRect(160, 20, 83, 16))
        self.SingleFile_radioButton.setObjectName("SingleFile_radioButton")
        self.PatFolder_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.PatFolder_radioButton.setGeometry(QtCore.QRect(65, 20, 83, 16))
        self.PatFolder_radioButton.setChecked(True)
        self.PatFolder_radioButton.setObjectName("PatFolder_radioButton")
        self.OpenPath_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OpenPath_lineEdit.setGeometry(QtCore.QRect(110, 130, 420, 21))
        self.OpenPath_lineEdit.setReadOnly(True)
        self.OpenPath_lineEdit.setObjectName("OpenPath_lineEdit")
        self.Period_label = QtWidgets.QLabel(self.centralwidget)
        self.Period_label.setGeometry(QtCore.QRect(110, 200, 100, 20))
        self.Period_label.setObjectName("Period_label")
        self.Analysis_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Analysis_pushButton.setGeometry(QtCore.QRect(110, 400, 101, 23))
        self.Analysis_pushButton.setObjectName("Analysis_pushButton")
        self.Open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Open_pushButton.setGeometry(QtCore.QRect(550, 130, 180, 23))
        self.Open_pushButton.setMouseTracking(False)
        self.Open_pushButton.setObjectName("Open_pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 460, 620, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.TopLinePercent_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TopLinePercent_lineEdit.setGeometry(QtCore.QRect(230, 260, 181, 20))
        self.TopLinePercent_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.TopLinePercent_lineEdit.setObjectName("TopLinePercent_lineEdit")
        self.TopLinePercent_label = QtWidgets.QLabel(self.centralwidget)
        self.TopLinePercent_label.setGeometry(QtCore.QRect(110, 260, 100, 20))
        self.TopLinePercent_label.setObjectName("TopLinePercent_label")
        self.LineLimitCount_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LineLimitCount_lineEdit.setGeometry(QtCore.QRect(551, 260, 181, 20))
        self.LineLimitCount_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LineLimitCount_lineEdit.setObjectName("LineLimitCount_lineEdit")
        self.LineLimitCount_label = QtWidgets.QLabel(self.centralwidget)
        self.LineLimitCount_label.setGeometry(QtCore.QRect(430, 260, 100, 20))
        self.LineLimitCount_label.setObjectName("LineLimitCount_label")
        self.CostTime_label = QtWidgets.QLabel(self.centralwidget)
        self.CostTime_label.setGeometry(QtCore.QRect(560, 490, 171, 21))
        self.CostTime_label.setText("")
        self.CostTime_label.setObjectName("CostTime_label")
        self.CollectData_label = QtWidgets.QLabel(self.centralwidget)
        self.CollectData_label.setGeometry(QtCore.QRect(110, 330, 100, 20))
        self.CollectData_label.setObjectName("CollectData_label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 320, 200, 40))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.Down_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Down_radioButton.setGeometry(QtCore.QRect(110, 10, 90, 20))
        self.Down_radioButton.setObjectName("Down_radioButton")
        self.Up_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Up_radioButton.setGeometry(QtCore.QRect(10, 10, 90, 20))
        self.Up_radioButton.setChecked(True)
        self.Up_radioButton.setObjectName("Up_radioButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pattern2EVCD"))
        self.ClockPinName_label.setText(_translate("MainWindow", "ClockPinName"))
        self.SingleFile_radioButton.setText(_translate("MainWindow", "SingleFile"))
        self.PatFolder_radioButton.setText(_translate("MainWindow", "PatFolder"))
        self.Period_label.setText(_translate("MainWindow", "Period(ps)"))
        self.Analysis_pushButton.setText(_translate("MainWindow", "Analysis"))
        self.Open_pushButton.setText(_translate("MainWindow", "Open"))
        self.TopLinePercent_lineEdit.setText(_translate("MainWindow", "100"))
        self.TopLinePercent_label.setText(_translate("MainWindow", "TopLinePercent(%)"))
        self.LineLimitCount_lineEdit.setText(_translate("MainWindow", "1000"))
        self.LineLimitCount_label.setText(_translate("MainWindow", "LineLimitCount"))
        self.CollectData_label.setText(_translate("MainWindow", "CollectData"))
        self.Down_radioButton.setText(_translate("MainWindow", "Down"))
        self.Up_radioButton.setText(_translate("MainWindow", "Up"))

